import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useCallback } from "react";
import { useNavigate } from "react-router-dom";
import { motion } from "framer-motion";
import { ArrowRight, Briefcase, DollarSign, Users } from "lucide-react";
import { addIncrementUserClicked } from "../../controller/userClickedController";
export default function JobCard({ job }) {
    const nav = useNavigate();
    const viewDetails = useCallback(() => {
        addIncrementUserClicked(job.id);
        nav("/jobs/" + job.id);
    }, [nav, job.id]);
    return (_jsx(motion.div, { whileHover: {
            scale: 1.03,
            boxShadow: "0 10px 20px rgba(128, 90, 213, 0.1)",
        }, className: "bg-white/80 backdrop-blur-sm \n                border border-purple-100/50 \n                rounded-xl \n                overflow-hidden \n                shadow-sm \n                transition-all \n                duration-300 \n                hover:border-purple-200\n                w-full\n                h-[250px]", children: _jsxs("div", { className: "p-5 flex flex-col h-full", children: [_jsxs("div", { className: "flex items-center justify-between mb-3", children: [_jsxs("h3", { className: "text-lg font-bold text-gray-800 flex items-center truncate", children: [_jsx(Briefcase, { className: "mr-2 text-purple-500 flex-shrink-0", size: 20 }), _jsx("span", { className: "truncate", children: job.jobName })] }), job.jobTags && job.jobTags.length > 0 && (_jsx("span", { className: "text-xs font-medium \n                            bg-purple-100 text-purple-700 \n                            px-2 py-1 rounded-full ml-2", children: job.jobTags[0].jobCategoryName }))] }), _jsxs("div", { className: "grid grid-cols-2 gap-2 mb-4 text-gray-600", children: [_jsxs("div", { className: "flex items-center", children: [_jsx(DollarSign, { className: "mr-1 text-green-500", size: 16 }), _jsxs("span", { className: "font-medium text-sm", children: ["$", job.jobSalary] })] }), _jsxs("div", { className: "flex items-center", children: [_jsx(Users, { className: "mr-1 text-blue-500", size: 16 }), _jsxs("span", { className: "font-medium text-sm", children: [Number(job.jobSlots), " Slots"] })] })] }), _jsxs("div", { className: "mb-4 flex-grow overflow-hidden", children: [_jsx("h4", { className: "text-xs font-semibold text-gray-700 mb-2", children: "Job Description" }), _jsxs("ul", { className: "text-gray-600 space-y-2 text-xs", children: [job.jobDescription.slice(0, 2).map((desc, index) => (_jsxs("li", { className: "flex items-start", children: [_jsx("span", { className: "w-1.5 h-1.5 mt-1 mr-2 bg-purple-300 rounded-full flex-shrink-0" }), _jsx("span", { className: "line-clamp-1", children: desc })] }, index))), job.jobDescription.length > 2 && (_jsxs("li", { className: "text-xs text-gray-500 ml-3", children: ["+ ", job.jobDescription.length - 2, " more details"] }))] })] }), _jsxs(motion.button, { whileHover: { scale: 1.05 }, whileTap: { scale: 0.95 }, onClick: viewDetails, className: "w-full flex items-center justify-center \n                        bg-gradient-to-r from-purple-500 to-blue-500 \n                        text-white \n                        py-2 \n                        rounded-lg \n                        hover:from-purple-600 hover:to-blue-600 \n                        transition-all \n                        text-sm\n                        duration-300\n                        font-medium", children: ["View Details", _jsx(ArrowRight, { className: "ml-1", size: 16 })] })] }) }));
}
