import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { motion } from 'framer-motion';
import { AlertTriangle, XCircle, CheckCircle } from 'lucide-react';
const FinishJobModal = ({ isOpen, onClose, onConfirm, isLoading }) => {
    if (!isOpen)
        return null;
    return (_jsx(motion.div, { className: "fixed inset-0 bg-black/30 backdrop-blur-sm z-50 flex items-center justify-center", initial: { opacity: 0 }, animate: { opacity: 1 }, exit: { opacity: 0 }, onClick: onClose, children: _jsxs(motion.div, { className: "bg-white rounded-2xl shadow-2xl p-8 max-w-md w-full", initial: { scale: 0.9, opacity: 0 }, animate: { scale: 1, opacity: 1 }, exit: { scale: 0.9, opacity: 0 }, onClick: (e) => e.stopPropagation(), children: [_jsxs("div", { className: "flex justify-between items-center mb-6", children: [_jsxs("h2", { className: "text-2xl font-bold text-indigo-800 flex items-center gap-2", children: [_jsx(AlertTriangle, { className: "text-amber-500", size: 24 }), "Finish Job"] }), _jsx("button", { onClick: onClose, className: "text-gray-500 hover:text-gray-800 transition-colors", disabled: isLoading, children: _jsx(XCircle, { size: 24 }) })] }), _jsxs("div", { className: "mb-6", children: [_jsx("div", { className: "p-4 bg-amber-50 border border-amber-200 rounded-xl mb-4", children: _jsx("p", { className: "text-amber-800 font-medium", children: "Are you sure you want to finish this job?" }) }), _jsx("p", { className: "text-gray-600", children: "This action will mark the job as completed and trigger payment to all accepted freelancers. This action cannot be undone." })] }), _jsxs("div", { className: "flex gap-4 justify-end", children: [_jsx("button", { onClick: onClose, className: "px-6 py-2 rounded-xl font-medium border border-gray-300 text-gray-700 hover:bg-gray-50 transition-colors", disabled: isLoading, children: "Cancel" }), _jsx("button", { onClick: onConfirm, className: "px-6 py-2 rounded-xl font-medium bg-gradient-to-r from-blue-600 to-indigo-600 text-white hover:from-blue-700 hover:to-indigo-700 transition-colors flex items-center gap-2", disabled: isLoading, children: isLoading ? (_jsxs(_Fragment, { children: [_jsx(motion.div, { className: "w-5 h-5 border-2 border-white/30 border-t-white rounded-full", animate: { rotate: 360 }, transition: {
                                            duration: 1,
                                            repeat: Infinity,
                                            ease: "linear",
                                        } }), "Processing..."] })) : (_jsxs(_Fragment, { children: [_jsx(CheckCircle, { size: 20 }), "Confirm"] })) })] })] }) }));
};
export default FinishJobModal;
